name: Docker image
env:
  platforms: linux/amd64,linux/arm64
  version: 1.3.1
on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up multiarch
      uses: docker/setup-qemu-action@v1
    - name: Set up BuildX
      uses: docker/setup-buildx-action@v1
    - uses: actions/checkout@v2
    - name: Docker login
      run: |
        echo ${GHCR_KEY} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        echo ${DOCKER_HUB_KEY} | docker login -u cmbdevopsbot --password-stdin
      env:
        GHCR_KEY: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
    - name: Build/Push Docker image
      run: | 
        docker buildx build --platform $platforms --push . --build-arg grpcui_version=${version} --file Dockerfile --tag ghcr.io/combinationab/grpcui-sidecar:v${version} --tag ghcr.io/combinationab/grpcui-sidecar:latest --tag  combination/grpcui-sidecar:v${version} --tag combination/grpcui-sidecar:latest
